### ISSUE TITLE
Problem with the comma when there are more than 1000 players online.

### ISSUE THREAD

**Issue by Pixelao** [Galarzaa90/tibia.py#22]
_Hello! Cipsoft added a comma in the world list when there are more than 1000 players online._

> File "\site-packages\tibiapy\world.py", line 267, in from_content
>     world._parse_world_info(tables.get("World Information", []))
> File "\site-packages\tibiapy\world.py", line 344, in _parse_world_info
>     self.online_count = int(world_info.pop("players_online"))
> **ValueError: invalid literal for int() with base 10: '1,024'**
>

**Comment by Galarzaa90** [comment]
Wow, 1000 players online. That's a surprise.

I'll fix it.

**Comment by Galarzaa90** [comment]
Fixed in v2.3.3
