### ISSUE TITLE
tibiapy.HousesSection.from_content is broken

### ISSUE THREAD

**Issue by aaronga97** [Galarzaa90/tibia.py#31]
**Problem**
Method `tibiapy.HousesSection.from_content`[(link to code)](https://github.com/Galarzaa90/tibia.py/blob/master/tibiapy/house.py#L149-#L195) throws `tibiapy.errors.InvalidContent` error instead of returning a `HousesSection` object.

The reason this unintended behavior happens is because we try to access a `Nonetype` object inside `HouseSection._parse_filters` [method](https://github.com/Galarzaa90/tibia.py/blob/master/tibiapy/house.py#L197) when we call it `house_results._parse_filters(tables["House Search"])` in [line 172](https://github.com/Galarzaa90/tibia.py/blob/master/tibiapy/house.py#L172).

**Quick fix**
Commenting [line 172](https://github.com/Galarzaa90/tibia.py/blob/master/tibiapy/house.py#L172) solves the issue for me (at least it does for my use case).

**Comment by Galarzaa90** [comment]
This is fixed on v5.5.2, thanks for the report.
