### ISSUE TITLE
Leaderboards are not correctly parsed when there are no results in Drome

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibia.py#34]
Marbera right now has no results for the Drome leaderboard.
This seems to cause issues:

```
venv/lib/python3.8/site-packages/tibiapy/leaderboard.py:174
not enough values to unpack (expected 3, got 1)
```

![image](https://github.com/Galarzaa90/tibia.py/assets/20662669/30e00847-c0ae-4c0e-a3dc-0a466dcca069)

**Comment by Tschis** [comment]
The same could be verified with other worlds that had no results, like Alumbra

Here is the snippet of the page when it has no results

https://gist.github.com/Tschis/1325e0c718cb89be32833a4e2e23bfc2

**Comment by Galarzaa90** [comment]
This is fixed in the latest version.
